apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: webscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: webscraper-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: AWS_ACCESS_KEY_ID
              value: "local"
            - name: AWS_SECRET_ACCESS_KEY
              value: "local"
            - name: AWS_REGION
              value: "eu-central-1"
            - name: DYNAMODB_ENDPOINT
              value: "http://dynamodb.webscraper:8000"
            - name: TABLE_NAME
              value: "Products"
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: webscraper
spec:
  selector:
    app: backend
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
