apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: webscraper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          # image: webscraper-frontend:latest # for minikube
          image: gcr.io/webscraper-gke/webscraper-frontend:latest
          # imagePullPolicy: Never #only for minikube
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: webscraper
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
